services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: recipe_db          # ✅ DB name
      POSTGRES_USER: recipe_user      # ✅ User name
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./back-diet/backend/demo
      dockerfile: Dockerfile
    environment:
      # Local DB
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipe_db
      
      # RAILWAY Keycloak (PROD)
      KEYCLOAK_URL: https://nutrifit-production-c4b6.up.railway.app
      KEYCLOAK_REALM: master
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Evafelmercedes25
      
      CALORIENINJAS_API_KEY: So5ir8D2mEwuN7rfmh/+vg==hl1oJdDWUceFzV84
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./front-diet/frontend
      dockerfile: Dockerfile
    environment:
      # Backend local + Keycloak Railway
      API_URL: http://localhost:8081
      KEYCLOAK_URL: https://nutrifit-production-c4b6.up.railway.app
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_ID: diet-frontend
    ports:
      - "80:80"
