version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: recipe-postgres
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-prod
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/recipe_db
      KC_DB_USERNAME: recipe_user
      KC_DB_PASSWORD: secret123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Evafelmercedes25
      KC_HOSTNAME: nutrifit-production-c4b6.up.railway.app
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  backend:
    build:
      context: ./back-diet/backend/demo
      dockerfile: Dockerfile
    container_name: backend-java
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipe_db
      DATASOURCE_USER: recipe_user
      DATASOURCE_PASSWORD: secret123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Evafelmercedes25
      AI_AGENT_URL: http://127.0.0.1:8000
      CALORIENINJAS_API_KEY: So5ir8D2mEwuN7rfmh/+vg==hl1oJdDWUceFzV84
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./front-diet/frontend
      dockerfile: Dockerfile
    container_name: frontend-angular
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:



# version: '3.8'

# services:
#   postgres:
#     image: postgres:16-alpine
#     container_name: recipe-postgres
#     environment:
#       POSTGRES_DB: recipe_db
#       POSTGRES_USER: recipe_user
#       POSTGRES_PASSWORD: secret123
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U recipe_user"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   keycloak:
#     image: quay.io/keycloak/keycloak:23.0.7
#     container_name: keycloak
#     environment:
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin123
#       # ✅ Realm + Client création auto
#       KEYCLOAK_REALM: diet-realm
#       KC_HOSTNAME: localhost
#       KC_HOSTNAME_PORT: 8082
#       KC_HTTP_ENABLED: "true"
#       KC_PROXY: passthrough
#     command: start-dev
#     ports:
#       - "8082:8080"
#     depends_on:
#       - postgres
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#       start_period: 90s
#     restart: unless-stopped

#   redis:
#     image: redis:7-alpine
#     container_name: redis-cache
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     restart: unless-stopped

# volumes:
#   postgres_data:
#   redis_data:



