server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

spring:
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:24270/railway
    username: postgres
    password: nozXcxuaFafFXvTHkcKYEyMbgZXxrGRe
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  # ✅ FLYWAY CONFIGURATION
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

  jpa:
    hibernate:
      ddl-auto: update  # ✅ CHANGE FROM 'update' TO 'validate' (Flyway gère les migrations)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20

  jackson:
    serialization:
      indent_output: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://nutrifit-production-c4b6.up.railway.app/realms/master
          jwk-set-uri: https://nutrifit-production-c4b6.up.railway.app/realms/master/protocol/openid-connect/certs

keycloak:
  server-url: https://nutrifit-production-c4b6.up.railway.app
  admin-username: admin
  admin-password: admin123
  admin-client-id: admin-cli

ai:
  agent:
    url:  https://agent-ia-production-7fb0.up.railway.app

calorieninjas:
  api:
    key: So5ir8D2mEwuN7rfmh/+vg==hl1oJdDWUceFzV84

web:
  cors:
    allowed-origins: https://front-end-production-0ec7.up.railway.app,https://app-diet-frontend-prod.up.railway.app,http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: '*'
    allow-credentials: true
    max-age: 3600

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO  # ✅ ADD THIS TO SEE FLYWAY LOGS
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# MinIO Configuration
r2:
  endpoint: https://a92262e7c6362aa064b3345772b0e86b.r2.cloudflarestorage.com
  accessKey: cf1ca939dfbacc8146581cd4d3731675
  secretKey: e377b09e42c0dd393e1fd4853ee6cc889e4f8dd3f0049f1211f4b61c97509266
  bucketName: nutrifit-image
